# Generated by Django 5.1.6 on 2025-03-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='User',
        ),
    ]
