# Generated by Django 5.1.6 on 2025-03-10 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_surname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="The phone number must contain 9 to 15 digits and may start with '+'", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Services', 'Services'), ('Other', 'Other')], max_length=13)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Big', 'Big')], max_length=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'Lead',
            },
        ),
    ]
