# Generated by Django 5.1.6 on 2025-03-10 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0003_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=255)),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Negotiation', 'Negotiation'), ('Proposal Sent', 'Proposal Sent'), ('Won', 'Won')], default='Prospecting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prime_biz_crm.lead')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'db_table': 'Pipeline',
            },
        ),
    ]
