# Generated by Django 5.1.6 on 2025-03-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0005_reminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterModelTable(
            name='reminder',
            table='Reminder',
        ),
    ]
