# Generated by Django 5.1.6 on 2025-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0006_alter_reminder_options_alter_reminder_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='top_lead',
            field=models.BooleanField(default=False),
        ),
    ]
