# Generated by Django 5.1.6 on 2025-03-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0007_lead_top_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
