# Generated by Django 5.1.6 on 2025-03-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0009_alter_reminder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_to_pipeline',
            field=models.BooleanField(default=False),
        ),
    ]
