# Generated by Django 5.1.6 on 2025-03-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0010_lead_converted_to_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
    ]
