# Generated by Django 5.1.6 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0011_remove_lead_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='lost_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Lost', 'Lost'), ('Won', 'Won')], default='Active', max_length=6),
        ),
    ]
