# Generated by Django 5.1.6 on 2025-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0012_pipeline_lost_date_pipeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
