# Generated by Django 5.1.6 on 2025-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0013_alter_reminder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
