# Generated by Django 5.1.6 on 2025-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0014_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='Prime Biz CRM Ltd, Unit 15, Tech Park Business Centre, 42 Innovation Street, London, EC1A 4J, PUnited Kingdom'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='+44 20 7946 0123', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
