# Generated by Django 5.1.6 on 2025-03-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0015_customuser_address_customuser_phone_lead_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='+442079460123', max_length=20),
        ),
    ]
