# Generated by Django 5.1.6 on 2025-03-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0017_customuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='Prime Biz CRM Ltd, Unit 15, Tech Park Business Centre, 42 Innovation Street, London, EC1A 4JP, United Kingdom'),
        ),
    ]
