# Generated by Django 5.1.6 on 2025-03-30 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_biz_crm', '0019_alter_lead_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
